DT = 0.001

AMBIENT_TEMPERATURE = 20.0
WALL_NAV_CODE = 1
VOID_NAV_CODE = 255

COOLING_TAU = 40.0
VENT_TAU = 8.0

COOLING_C2 = 5e-4
VENT_C2 = 2e-3

GRID_MARGIN = 40
SAFE_ZONE_RADIUS = 20
DEFAULT_WALL_FUEL = 6.0
DOOR_FUEL_WINDOW = 1.0
DOOR_FUEL_DOOR = 3.0

EX_MIN = 0.2
EX_MAX = 2.0

MAX_TEMPERATURE = 1500.0


class SimulationConstants:
    DT = DT
    AMBIENT_TEMPERATURE = AMBIENT_TEMPERATURE
    WALL_NAV_CODE = WALL_NAV_CODE
    VOID_NAV_CODE = VOID_NAV_CODE
    MAX_TEMPERATURE = MAX_TEMPERATURE
